// import React, { useState } from 'react';
// import './App.css';
// // Imports the Amplify library from 'aws-amplify' package. This is used to configure your app to interact with AWS services.
// import { Amplify } from 'aws-amplify';
// import { Authenticator, withAuthenticator } from '@aws-amplify/ui-react';
// // Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
// import '@aws-amplify/ui-react/styles.css';

// // Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.
// import awsExports from './aws-exports';
// Amplify.configure(awsExports);

// // Sample product data (in a real app, this would come from your backend)
// const products = [
//   { id: 1, name: "Product 1", price: 19.99, image: "https://via.placeholder.com/150" },
//   { id: 2, name: "Product 2", price: 29.99, image: "https://via.placeholder.com/150" },
//   { id: 3, name: "Product 3", price: 39.99, image: "https://via.placeholder.com/150" },
// ];

// function App() {
//   const [cart, setCart] = useState([]);

//   const addToCart = (product) => {
//     setCart([...cart, product]);
//   };

//   const cartTotal = cart.reduce((total, item) => total + item.price, 0).toFixed(2);

//   return (
//     <div className="App">
//       <Authenticator>
//         {({ signOut }) => (
//           <main>
//             <header className='App-header'>
//               <h1>Simple E-Commerce Store</h1>
//               <div className="product-list">
//                 {products.map(product => (
//                   <div key={product.id} className="product">
//                     <img src={product.image} alt={product.name} />
//                     <h3>{product.name}</h3>
//                     <p>${product.price}</p>
//                     <button onClick={() => addToCart(product)}>Add to Cart</button>
//                   </div>
//                 ))}
//               </div>
//               <div className="cart">
//                 <h2>Cart</h2>
//                 <ul>
//                   {cart.map((item, index) => (
//                     <li key={index}>{item.name} - ${item.price}</li>
//                   ))}
//                 </ul>
//                 <p>Total: ${cartTotal}</p>
//               </div>
//               <button
//                 onClick={signOut}
//                 style={{
//                   margin: '20px',
//                   fontSize: '0.8rem',
//                   padding: '5px 10px',
//                   marginTop: '20px'
//                 }}
//               >
//                 Sign Out
//               </button>
//             </header>
//           </main>
//         )}
//       </Authenticator>
//     </div>
//   );
// }

// export default withAuthenticator(App);

// -----------------------------------------------------------------------------------------------------------------------------------------------------------

// import React, { useState } from 'react';

// const App = () => {
//   // Sample product data
//   const products = [
//     { id: 1, name: 'Product 1', price: 100 },
//     { id: 2, name: 'Product 2', price: 150 },
//     { id: 3, name: 'Product 3', price: 200 },
//   ];

//   // State for cart and order
//   const [cart, setCart] = useState([]);
//   const [orderPlaced, setOrderPlaced] = useState(false);

//   // Add product to cart
//   const addToCart = (product) => {
//     setCart([...cart, product]);
//   };

//   // Place order and clear cart
//   const placeOrder = () => {
//     if (cart.length > 0) {
//       setOrderPlaced(true);
//       setCart([]); // Clear cart after placing order
//     } else {
//       alert('Your cart is empty.');
//     }
//   };
//   return (
//     <div className="App">
//       <h1>Simple E-commerce</h1>

//       {/* Product List */}
//       <h2>Products</h2>
//       <div>
//         {products.map((product) => (
//           <div key={product.id}>
//             <h3>{product.name}</h3>
//             <p>Price: ${product.price}</p>
//             <button onClick={() => addToCart(product)}>Add to Cart</button>
//           </div>
//         ))}
//       </div>

//       {/* Cart */}
//       <h2>Your Cart</h2>
//       {cart.length > 0 ? (
//         cart.map((item, index) => (
//           <div key={index}>
//             <p>{item.name} - ${item.price}</p>
//           </div>
//         ))
//       ) : (
//         <p>Your cart is empty.</p>
//       )}

//       {/* Place Order Button */}
//       <button onClick={placeOrder}>Place Order</button>

//       {/* Order Confirmation */}
//       {orderPlaced && <h3>Order Placed Successfully!</h3>}
//     </div>
//   );
// };

// export default App

// -----------------------------------------------------------------------------------------------------------------------------------------------------------
import React, { useState } from "react";

const App = () => {
  // Sample product data
  const products = [
    { id: 1, name: "Product 1", price: 100 },
    { id: 2, name: "Product 2", price: 150 },
    { id: 3, name: "Product 3", price: 200 },
  ];

  // State for cart and order
  const [cart, setCart] = useState([]);
  const [orderPlaced, setOrderPlaced] = useState(false);

  // API endpoint URL (replace with your actual API Gateway URL)
  const apiUrl =
    "https://your-api-id.execute-api.region.amazonaws.com/your-stage/cart";

  // Add product to cart
  const addToCart = async (product) => {
    try {
      const response = await fetch(apiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          CartID: "user123", // Replace with dynamic user ID if applicable
          ProductID: product.id.toString(),
          Quantity: 1, // Adjust quantity as needed
          Price: product.price,
        }),
      });

      const result = await response.json();
      if (response.ok) {
        setCart((prevCart) => [...prevCart, product]);
        alert("Product added to cart successfully!");
      } else {
        alert(`Failed to add product: ${result.message}`);
      }
    } catch (error) {
      console.error("Error adding product to cart:", error);
      alert("Error adding product to cart.");
    }
  };

  // Place order and clear cart
  const placeOrder = () => {
    if (cart.length > 0) {
      setOrderPlaced(true);
      setCart([]); // Clear cart after placing order
    } else {
      alert("Your cart is empty.");
    }
  };

  return (
    <div className="App">
      <h1>Simple E-commerce</h1>

      {/* Product List */}
      <h2>Products</h2>
      <div>
        {products.map((product) => (
          <div key={product.id}>
            <h3>{product.name}</h3>
            <p>Price: ${product.price}</p>
            <button onClick={() => addToCart(product)}>Add to Cart</button>
          </div>
        ))}
      </div>

      {/* Cart */}
      <h2>Your Cart</h2>
      {cart.length > 0 ? (
        cart.map((item, index) => (
          <div key={index}>
            <p>
              {item.name} - ${item.price}
            </p>
          </div>
        ))
      ) : (
        <p>Your cart is empty.</p>
      )}

      {/* Place Order Button */}
      <button onClick={placeOrder}>Place Order</button>

      {/* Order Confirmation */}
      {orderPlaced && <h3>Order Placed Successfully!</h3>}
    </div>
  );
};

export default App;
